insert into spareship.spare_parts (sku_id, category, description)
values  (1, 'PCB-MB', 'Motherboard-WZID'),
        (2, 'Mainboard', 'Mainboard Assy-Redmi Note5 Pro-IN-6+64G'),
        (3, 'Mainboard', 'Mainboard Assy-Redmi Note5 Pro-IN-4+64G'),
        (4, 'Mainboard', 'Mainboard Assy-Redmi Note5-IN-4+64G-2.0'),
        (5, 'Mainboard', 'Mainboard Assy-Redmi Note5-IN-3+32G-2.0'),
        (6, 'Mainboard', 'Mainboard Assy-Redmi Note 5-IN-4+64G-1.0'),
        (7, 'Mainboard', 'Mainboard Assy-Redmi Note 5-IN-3+32G-1.0'),
        (8, 'Mainboard', 'Mainboard Assy-Redmi6-IN-3GB+64GB'),
        (9, 'Mainboard', 'Mainboard Assy-Redmi6-IN-3GB+32GB'),
        (10, 'Mainboard', 'Mainboard Assy-Redmi7-IN-2GB+32GB'),
        (11, 'Mainboard', 'Mainboard Assy-Redmi7-IN-3GB+32GB'),
        (12, 'Mainboard', 'Mainboard Assy-RedmiY2-IN-4GB+64GB'),
        (13, 'Mainboard', 'Mainboard Assy-RedmiY2-IN-3GB+32GB'),
        (14, 'Mainboard', 'Mainboard Assy-Mi A2-IN-6+128G'),
        (15, 'Mainboard', 'Mainboard Assy-Mi A2-IN-4+64G'),
        (16, 'Mainboard', 'Mainboard Assy-Redmi9-IN-4GB+128GB'),
        (17, 'Mainboard', 'Mainboard Assy-Redmi9-IN-4GB+64GB'),
        (18, 'Mainboard', 'Mainboard Assy-Redmi 3S-N/A-IN-32G'),
        (19, 'Mainboard', 'Mainboard Assy-Redmi 3S-IN-16G'),
        (20, 'Mainboard', 'Mainboard Assy-Redmi 3S-IN-32G'),
        (21, 'Mainboard', 'Mainboard Assy - Pocco F1 - 8+256G'),
        (22, 'Mainboard', 'Mainboard Assy - Pocco F1 - 6+64G'),
        (23, 'Mainboard', 'Mainboard Assy - Pocco F1 - 6+128G'),
        (24, 'LCD Module', 'Front Cover Display Module-F6L-IN-Blue'),
        (25, 'LCD Module', 'Front Cover Display Module-F6L-IN-Black'),
        (26, 'LCD Module', 'Front Cover Display Module-F6L-IN-White'),
        (27, 'LCD Module', 'Front Cover Display Module-Redmi - black'),
        (28, 'LCD Module', 'Front Cover Display Module-Redmi - White'),
        (29, 'LCD Module', 'Front Cover Display Module - Black'),
        (30, 'LCM', 'LCD Module'),
        (31, 'LCM', 'Front Cover Display Module - All Colour'),
        (32, 'LCM', 'Front Cover Display Module-Redmi Y2-White'),
        (33, 'LCM', 'Front Cover Display Module-Redmi Y2-black'),
        (34, 'LCM', 'Front Cover Display Module-Redmi Note5-White'),
        (35, 'LCM', 'Front Cover Display Module-Redmi Note5-black'),
        (36, 'Battery', 'Battery Mini'),
        (37, 'Battery', 'Battery N'),
        (38, 'Battery', 'Battery Pro'),
        (39, 'Battery', 'Battery-POCO F1'),
        (40, 'Camera', 'Camera 64 MP AI enhanced'),
        (41, 'Camera', 'Camera 64 MP'),
        (42, 'Camera', 'Camera 32 MP'),
        (43, 'Camera', 'Camera Macro Lens'),
        (44, 'Camera', 'Camera 16 MP Front'),
        (45, 'Camera', 'Camera 12 MP Front');